library(MASS)
library(ISLR)
MASS::Cars93
A = data.frame(Cars93)
str(A)
hist(A$Manufacturer)
str(A)
hist(A$RPM)
A1 = A[1:20,]
A1
hist(A1$RPM)
A1
A1$RPM
table(A1$RPM)
table(A1$RPM)
table(A1$RPM,col = 2)
table(A1$RPM,col = 2:10)
table(A1$RPM,col = 1:5)
hist(A1$RPM,col = 1:5)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = c(2,2,2,2,9))
hist(A1$RPM,col = c(2,2,2,2,3))
par(mfrow=c(2,2)) # We can put multiple graphs in a single plot by setting some graphical parameters with the help of par() function. and Graphical parameter "mfrow" can be used to specify the number of subplot we need.
hist(A1$RPM,col = c(2,2,2,2,3))
hist(A1$RPM,col = c(2,2,2,2,3))
hist(A1$RPM,col = c(2,2,2,2,3))
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 1)
hist(A1$RPM,col = 2)
hist(A1$RPM,col = 3)
hist(A1$RPM,col = 4)
par(mfrow=c(3,2))
hist(A1$RPM,col = 4)
hist(A1$RPM,col = 42)

hist(A1$RPM,col = 3)
hist(A1$RPM,col = 4)
hist(A1$RPM,col = 5)
hist(A1$RPM,col = 6)
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency")
par(mfrow=c(1,1))
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency")
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines")
hist(A1$RPM,col = 3,main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines",ylab = "Repetation frequency")
hist(A1$RPM,col = "blue",main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines",ylab = "Repetation frequency")
?hist
hist(A1$RPM,col = "blue",main = "Histogram of RPM's with repeat frequency",xlab = "RPM of engines",ylab = "Repetation frequency",labels = TRUE,breaks = seq(4000,7000,200))
A = data.frame(iris)
A
str(A)
hist(A$Species)
A = data.frame(ISLR::Wage)
hist(A$age)
hist(A$age,main = "Histogram of Age over population")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 2)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 3)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 4)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = "black")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = "brown")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = "purple")
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:13)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3,breaks = seq(0,100,10))
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3,xlim = 500)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3,xlim = 1000)
hist(A$age,main = "Histogram of Age over population",xlab = "Age of person",ylab = "Number of people",col = 1:3)